apiVersion: v1
kind: Service
metadata:
  name: pgadmin4-service
  labels:
    app: pgadmin4
spec:
  selector:
    app: pgadmin4
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: pgadmin4
