apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - protocol: TCP
    nodePort: 30001
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
